return {
    ["[RAGE] Rem`s Config"] = {
        objects = {
            { idx = "animation_player_enabled", type = "Toggle", value = true },
            { idx = "target_highlight", type = "Toggle", value = false },
            { idx = "indicator_manipulated", type = "Toggle", value = true },
            { idx = "viewmodel_override_appearance", type = "Toggle", value = false },
            { idx = "lighting_toggle_ClockTime", type = "Toggle", value = true },
            { idx = "ragebot_enabled", type = "Toggle", value = true },
            { idx = "movement_noclip", type = "Toggle", value = true },
            { idx = "silent_closest_part", type = "Toggle", value = false },
            { idx = "KeybindMenu", type = "Toggle", value = true },
            { idx = "camera_fov_changer", type = "Toggle", value = true },
            { idx = "arm_override_appearance", type = "Toggle", value = false },
            { idx = "esp_skeleton_outline", type = "Toggle", value = false },
            { idx = "auto_load_enabled", type = "Toggle", value = false },
            { idx = "silent_fov_fill", type = "Toggle", value = true },
            { idx = "esp_chams", type = "Toggle", value = true },
            { idx = "viewmodel_body_color", type = "Toggle", value = false },
            { idx = "lighting_toggle_ColorShift_Top", type = "Toggle", value = false },
            { idx = "lighting_toggle_FogEnd", type = "Toggle", value = false },
            { idx = "silent_fov_outline", type = "Toggle", value = true },
            { idx = "lighting_toggle_ColorShift_Bottom", type = "Toggle", value = true },
            { idx = "NotificationColors", type = "Toggle", value = false },
            { idx = "movement_infinite_double_jump", type = "Toggle", value = true },
            { idx = "exploits_full_auto", type = "Toggle", value = true },
            { idx = "spoof_device_enabled", type = "Toggle", value = false },
            { idx = "hit_sounds_enabled", type = "Toggle", value = true },
            { idx = "lighting_toggle_Ambient", type = "Toggle", value = true },
            { idx = "atmosphere_enabled", type = "Toggle", value = true },
            { idx = "auto_queue_enabled", type = "Toggle", value = false },
            { idx = "ragebot_priority", type = "Toggle", value = true },
            { idx = "viewmodel_offset", type = "Toggle", value = true },
            { idx = "shoot_sound_change", type = "Toggle", value = true },
            { idx = "viewmodel_disable_textures", type = "Toggle", value = false },
            { idx = "indicator_ammo", type = "Toggle", value = true },
            { idx = "target_ui_enabled", type = "Toggle", value = false },
            { idx = "hit_effects_weld", type = "Toggle", value = false },
            { idx = "anti_aim_floor_hide", type = "Toggle", value = true },
            { idx = "viewmodel_wireframe", type = "Toggle", value = false },
            { idx = "aimbot_fov_outline", type = "Toggle", value = true },
            { idx = "esp_healthbar", type = "Toggle", value = true },
            { idx = "movement_velocity", type = "Toggle", value = true },
            { idx = "arm_disable_textures", type = "Toggle", value = false },
            { idx = "aimbot_fov_fill", type = "Toggle", value = true },
            { idx = "autoban_maps", type = "Toggle", value = true },
            { idx = "hit_sounds_disable", type = "Toggle", value = true },
            { idx = "custom_tracer_outline", type = "Toggle", value = false },
            { idx = "camera_aspect_ratio", type = "Toggle", value = false },
            { idx = "aimbot_fov_moving", type = "Toggle", value = false },
            { idx = "chat_spam_enabled", type = "Toggle", value = false },
            { idx = "crosshair_disable_game", type = "Toggle", value = true },
            { idx = "triggerbot_enabled", type = "Toggle", value = false },
            { idx = "lighting_toggle_Brightness", type = "Toggle", value = true },
            { idx = "auto_select_enabled", type = "Toggle", value = true },
            { idx = "esp_show_team", type = "Toggle", value = false },
            { idx = "aimbot_toggle", type = "Toggle", value = false },
            { idx = "viewmodel_frames_override", type = "Toggle", value = false },
            { idx = "aimbot_match_axis", type = "Toggle", value = false },
            { idx = "arm_body_color", type = "Toggle", value = false },
            { idx = "esp_skeleton", type = "Toggle", value = true },
            { idx = "third_person_enabled", type = "Toggle", value = true },
            { idx = "target_hit_notify", type = "Toggle", value = true },
            { idx = "silent_manipulation", type = "Toggle", value = true },
            { idx = "esp_override_appearance", type = "Toggle", value = false },
            { idx = "lighting_bool_GlobalShadows", type = "Toggle", value = true },
            { idx = "silent_toggle", type = "Toggle", value = true },
            { idx = "skybox_enabled", type = "Toggle", value = true },
            { idx = "auto_load_silent", type = "Toggle", value = false },
            { idx = "esp_world_distance", type = "Toggle", value = true },
            { idx = "esp_world_name", type = "Toggle", value = true },
            { idx = "targeting_visibleonly", type = "Toggle", value = true },
            { idx = "color_correction_enabled", type = "Toggle", value = true },
            { idx = "movement_slideboost", type = "Toggle", value = true },
            { idx = "autoban_weapons", type = "Toggle", value = true },
            { idx = "esp_effects_particle", type = "Toggle", value = true },
            { idx = "crosshair_outline", type = "Toggle", value = true },
            { idx = "arcade_auto_respawn", type = "Toggle", value = true },
            { idx = "ragebot_priority_notification", type = "Toggle", value = true },
            { idx = "esp_effects_aura", type = "Toggle", value = false },
            { idx = "esp_name", type = "Toggle", value = true },
            { idx = "sunrays_enabled", type = "Toggle", value = false },
            { idx = "esp_world_image", type = "Toggle", value = true },
            { idx = "hit_effects_enabled", type = "Toggle", value = true },
            { idx = "viewmodel_material", type = "Toggle", value = false },
            { idx = "NotificationClips", type = "Toggle", value = false },
            { idx = "esp_fill_moving", type = "Toggle", value = true },
            { idx = "esp_body_color", type = "Toggle", value = false },
            { idx = "esp_healthbar_moving", type = "Toggle", value = false },
            { idx = "chat_spam_order", type = "Toggle", value = false },
            { idx = "silent_showfov", type = "Toggle", value = true },
            { idx = "esp_flag_health_text", type = "Toggle", value = false },
            { idx = "esp_weapon", type = "Toggle", value = true },
            { idx = "esp_healthbar_resize", type = "Toggle", value = false },
            { idx = "hit_effects_disable_marker", type = "Toggle", value = true },
            { idx = "movement_maul_slam", type = "Toggle", value = false },
            { idx = "item_remove_vignette", type = "Toggle", value = true },
            { idx = "hit_effects_disable_numbers", type = "Toggle", value = true },
            { idx = "name_spoofer", type = "Toggle", value = false },
            { idx = "arcade_auto_ammo", type = "Toggle", value = true },
            { idx = "esp_flag_staring_text", type = "Toggle", value = false },
            { idx = "anti_aim_enabled", type = "Toggle", value = true },
            { idx = "aimbot_showfov", type = "Toggle", value = false },
            { idx = "targeting_ignore_protected", type = "Toggle", value = true },
            { idx = "lighting_toggle_FogColor", type = "Toggle", value = false },
            { idx = "targeting_limitdistance", type = "Toggle", value = false },
            { idx = "exploits_always_backstab", type = "Toggle", value = true },
            { idx = "targeting_disableflash", type = "Toggle", value = false },
            { idx = "silent_fov_moving", type = "Toggle", value = true },
            { idx = "movement_fly", type = "Toggle", value = true },
            { idx = "weather_enabled", type = "Toggle", value = true },
            { idx = "esp_box", type = "Toggle", value = false },
            { idx = "esp_material", type = "Toggle", value = false },
            { idx = "movement_double_jump_height", type = "Toggle", value = true },
            { idx = "custom_tracer_enabled", type = "Toggle", value = true },
            { idx = "aimbot_delay_position", type = "Toggle", value = false },
            { idx = "arm_material", type = "Toggle", value = false },
            { idx = "esp_distance", type = "Toggle", value = true },
            { idx = "ragebot_void_spam", type = "Toggle", value = true },
            { idx = "lighting_toggle_ExposureCompensation", type = "Toggle", value = true },
            { idx = "target_tracer", type = "Toggle", value = false },
            { idx = "crosshair_enabled", type = "Toggle", value = true },
            { idx = "esp_box_moving", type = "Toggle", value = false },
            { idx = "ambience_enabled", type = "Toggle", value = true },
            { idx = "item_status_enabled", type = "Toggle", value = true },
            { idx = "viewmodel_chams", type = "Toggle", value = true },
            { idx = "silent_visualize", type = "Toggle", value = true },
            { idx = "indicator_ragebot", type = "Toggle", value = true },
            { idx = "aimbot_closest_part", type = "Toggle", value = false },
            { idx = "esp_fill", type = "Toggle", value = false },
            { idx = "camera_anti_flashbang", type = "Toggle", value = true },
            { idx = "exploits_no_spread", type = "Toggle", value = true },
            { idx = "lighting_toggle_FogStart", type = "Toggle", value = false },
            { idx = "bloom_enabled", type = "Toggle", value = true },
            { idx = "esp_healthbar_type", type = "Dropdown", mutli = false, value = "gradient" },
            { idx = "ragebot_keybind", type = "KeyPicker", key = "...", mode = "Always" },
            { idx = "triggerbot_keybind", type = "KeyPicker", key = "MB2", mode = "Hold" },
            { idx = "crosshair_offset", type = "Slider", value = "5" },
            { idx = "bloom_threshold", type = "Slider", value = "0.85" },
            { idx = "indicator_ragebot_text_color", type = "ColorPicker", transparency = 0, value = "f296ee" },
            { idx = "movement_velocityvalue", type = "Slider", value = "50" },
            { idx = "silent_outline_color1", type = "ColorPicker", transparency = 0.786363636363636, value = "c576bd" },
            { idx = "silent_fov_rotation", type = "Slider", value = "0" },
            { idx = "esp_effects_aura_color1", type = "ColorPicker", transparency = 0, value = "f296ee" },
            { idx = "silent_color2", type = "ColorPicker", transparency = 0, value = "e4c4ca" },
            { idx = "esp_flag_bridge", type = "Input", text = ": " },
            { idx = "esp_fill_rotation_speed", type = "Slider", value = "0.5" },
            { idx = "esp_effects_particle_color3", type = "ColorPicker", transparency = 0, value = "f296ee" },
            { idx = "indicator_ammo_style", type = "Dropdown", mutli = true, value = { ["ammo"] = true, ["max ammo"] = true, ["reserve"] = true } },
            { idx = "triggerbot_scoped", type = "Dropdown", mutli = true, value = { ["Sniper"] = true, ["Crossbow"] = true } },
            { idx = "shoot_sound_speed", type = "Slider", value = "1" },
            { idx = "aimbot_fov_rotation_speed", type = "Slider", value = "1" },
            { idx = "esp_weapon_rotation", type = "Slider", value = "0" },
            { idx = "NotificationStyleSortOrder", type = "Dropdown", mutli = false, value = "Default" },
            { idx = "crosshair_bounce", type = "Slider", value = "5" },
            { idx = "aimbot_fov_rotation", type = "Slider", value = "0" },
            { idx = "bloom_size", type = "Slider", value = "50" },
            { idx = "ragebot_weapon", type = "Dropdown", value = "primary" },
            { idx = "indicator_lerp", type = "Slider", value = "0.25" },
            { idx = "aimbot_color3", type = "ColorPicker", transparency = 0, value = "d7a6c3" },
            { idx = "viewmodel_offset_z", type = "Slider", value = "-0.7" },
            { idx = "aimbot_outline_color2", type = "ColorPicker", transparency = 0.7, value = "e38bde" },
            { idx = "auto_select_Secondary", type = "Dropdown", value = "Bow" },
            { idx = "silent_outline_color2", type = "ColorPicker", transparency = 0.7, value = "e38cde" },
            { idx = "skybox_disable", type = "Dropdown", mutli = true, value = {} },
            { idx = "esp_name_color1", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_flag_health_text_color1", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "auto_select_Primary", type = "Dropdown", value = "Daggers" },
            { idx = "aimbot_delay_smooth_x", type = "Slider", value = "4" },
            { idx = "viewmodel_chams_settings", type = "Dropdown", mutli = true, value = { ["through walls"] = true } },
            { idx = "esp_world_distance_color", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "aimbot_fill_color2", type = "ColorPicker", transparency = 1, value = "000000" },
            { idx = "esp_world_object_scale", type = "Slider", value = "75" },
            { idx = "esp_chams_color2", type = "ColorPicker", transparency = 0, value = "ff4ded" },
            { idx = "NotificationBarStyle", type = "Dropdown", mutli = false, value = "Top" },
            { idx = "movement_flyvalue", type = "Slider", value = "100" },
            { idx = "silent_keybind", type = "KeyPicker", key = "LeftAlt", mode = "Always" },
            { idx = "spoof_device_type", type = "Dropdown", value = "controller" },
            { idx = "esp_chams_color", type = "ColorPicker", transparency = 0, value = "000000" },
            { idx = "esp_fill_color3", type = "ColorPicker", transparency = 1, value = "000000" },
            { idx = "chat_spam_text", type = "Dropdown", mutli = true, value = {} },
            { idx = "arm_material_value", type = "Dropdown", value = "ForceField" },
            { idx = "triggerbot_settings", type = "Dropdown", mutli = true, value = { ["no delay between targets"] = true, ["anti katana"] = true } },
            { idx = "custom_tracer_selected", type = "Dropdown", mutli = false, value = "lightning" },
            { idx = "esp_name_rotation", type = "Slider", value = "0" },
            { idx = "anti_aim_yaw", type = "Dropdown", value = "random" },
            { idx = "animation_player_keybind", type = "KeyPicker", key = "...", mode = "Toggle" },
            { idx = "NotificationColorsFont", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "silent_color1", type = "ColorPicker", transparency = 1, value = "ffffff" },
            { idx = "viewmodel_offset_y", type = "Slider", value = "0" },
            { idx = "ragebot_void_spam_attack", type = "Slider", value = "0.01" },
            { idx = "target_ui_position_x", type = "Slider", value = "50" },
            { idx = "aimbot_delay_smooth_y", type = "Slider", value = "4" },
            { idx = "shoot_sound_volume", type = "Slider", value = "1" },
            { idx = "weather_rate_multiplier", type = "Slider", value = "1" },
            { idx = "esp_weapon_color3", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_world_whitelist", type = "Dropdown", mutli = true, value = { ["Flashbang"] = true, ["Smoke Grenade"] = true, ["Satchel"] = true, ["Subspace Tripmine"] = true, ["Molotov"] = true, ["Grenade"] = true } },
            { idx = "weather_color_2", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "silent_outline_color3", type = "ColorPicker", transparency = 0.268181818181818, value = "f296ee" },
            { idx = "esp_body_color_value", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_healthbar_color_end", type = "ColorPicker", transparency = 0, value = "9d539b" },
            { idx = "indicator_text_style", type = "Dropdown", mutli = false, value = "lower" },
            { idx = "esp_chams_alpha_outline", type = "Slider", value = "1" },
            { idx = "item_status_override", type = "Dropdown", value = "Prime" },
            { idx = "custom_tracer_fade", type = "Slider", value = "1" },
            { idx = "target_ui_show_targets", type = "Dropdown", mutli = true, value = {} },
            { idx = "viewmodel_chams_color2", type = "ColorPicker", transparency = 0, value = "d8e9ff" },
            { idx = "custom_tracer_position_lerp", type = "Slider", value = "0.5" },
            { idx = "indicator_manipulated_color", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "NotificationClipsDistance", type = "Slider", value = "200" },
            { idx = "arm_body_color_value", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "indicator_reserve_color", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "custom_tracer_color", type = "ColorPicker", transparency = 0, value = "c47cc1" },
            { idx = "esp_weapon_color2", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "crosshair_outline_color_1", type = "ColorPicker", transparency = 0, value = "000000" },
            { idx = "indicator_empty_color", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_skeleton_color1", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_name_font", type = "Dropdown", mutli = false, value = "default" },
            { idx = "animation_player_start_position", type = "Slider", value = "0" },
            { idx = "esp_box_color3", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_world_lerp_speed", type = "Slider", value = "0.1" },
            { idx = "esp_chams_settings", type = "Dropdown", mutli = true, value = {} },
            { idx = "lighting_number_ClockTime", type = "Slider", value = "0" },
            { idx = "targeting_forgettime", type = "Slider", value = "0" },
            { idx = "ragebot_priority_settings", type = "Dropdown", mutli = true, value = { ["voided players"] = true, ["attackers"] = true } },
            { idx = "esp_flag_style", type = "Dropdown", mutli = false, value = "upper" },
            { idx = "esp_healthbar_speed", type = "Slider", value = "1" },
            { idx = "esp_effects_aura_color3", type = "ColorPicker", transparency = 0, value = "f296ee" },
            { idx = "esp_distance_color1", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "exploits_grenade_settings", type = "Dropdown", mutli = true, value = {} },
            { idx = "esp_bounds_width_scale", type = "Slider", value = "100" },
            { idx = "NotificationAnchorStyle", type = "Dropdown", mutli = false, value = "Center" },
            { idx = "arm_body_transparency", type = "Slider", value = "100" },
            { idx = "autoban_first", type = "Dropdown", value = "Riot Shield" },
            { idx = "color_correction_contrast", type = "Slider", value = "0" },
            { idx = "hit_effects_material", type = "Dropdown", mutli = false, value = "ForceField" },
            { idx = "atmosphere_haze", type = "Slider", value = "10" },
            { idx = "triggerbot_part_blacklist", type = "Dropdown", mutli = true, value = {} },
            { idx = "hit_sounds_volume", type = "Slider", value = "0.9" },
            { idx = "indicator_offset_y", type = "Slider", value = "25" },
            { idx = "NotificationColorsMain", type = "ColorPicker", transparency = 0, value = "1c1c1c" },
            { idx = "viewmodel_offset_x", type = "Slider", value = "0" },
            { idx = "viewmodel_chams_alpha_outline", type = "Slider", value = "1" },
            { idx = "indicator_ammo_color", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "crosshair_outline_color_2", type = "ColorPicker", transparency = 0, value = "000000" },
            { idx = "esp_flag_staring_text_color1", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "aimbot_outline_color3", type = "ColorPicker", transparency = 0.268181818181818, value = "f296ee" },
            { idx = "triggerbot_max_distance", type = "Slider", value = "250" },
            { idx = "silent_fov_settings", type = "Dropdown", mutli = true, value = { ["position on target"] = true } },
            { idx = "sunrays_intensity", type = "Slider", value = "0.25" },
            { idx = "custom_tracer_lifetime", type = "Slider", value = "1" },
            { idx = "esp_healthbar_color_start", type = "ColorPicker", transparency = 0, value = "fbb8f8" },
            { idx = "triggerbot_reaction_time_offset", type = "Slider", value = "5" },
            { idx = "bloom_intensity", type = "Slider", value = "1.38" },
            { idx = "aimbot_color1", type = "ColorPicker", transparency = 1, value = "ffffff" },
            { idx = "auto_select_Utility", type = "Dropdown", value = "Riot Shield" },
            { idx = "KeybindMenuValue", type = "Dropdown", mutli = false, value = "Active" },
            { idx = "esp_healthbar_slices", type = "Slider", value = "1" },
            { idx = "crosshair_bounce_speed", type = "Slider", value = "2.9" },
            { idx = "anti_aim_pitch", type = "Dropdown", value = "random" },
            { idx = "lighting_colorFogColor", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "weather_timescale_multiplier", type = "Slider", value = "1" },
            { idx = "esp_body_disables", type = "Dropdown", mutli = true, value = {} },
            { idx = "viewmodel_material_value", type = "Dropdown", value = "ForceField" },
            { idx = "esp_fill_rotation", type = "Slider", value = "45" },
            { idx = "viewmodel_chams_alpha_fill", type = "Slider", value = "-1.6" },
            { idx = "aimbot_radius", type = "Slider", value = "1000" },
            { idx = "target_ui_item_scale", type = "Slider", value = "170" },
            { idx = "esp_world_name_color", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "triggerbot_forget_time", type = "Slider", value = "1.5" },
            { idx = "weather_lifetime_multiplier", type = "Slider", value = "100" },
            { idx = "hit_effects_col_3", type = "ColorPicker", transparency = 0, value = "f296ee" },
            { idx = "target_highlight_outline", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_distance_rotation", type = "Slider", value = "0" },
            { idx = "target_ui_scale", type = "Slider", value = "170" },
            { idx = "crosshair_rotation_speed", type = "Slider", value = "0.2" },
            { idx = "color_correction_saturation", type = "Slider", value = "1" },
            { idx = "movement_flykeybind", type = "KeyPicker", key = "X", mode = "Toggle" },
            { idx = "NotificationTransparency", type = "Slider", value = "35" },
            { idx = "esp_skeleton_color3", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "shoot_sound_start", type = "Slider", value = "0" },
            { idx = "esp_font", type = "Dropdown", mutli = false, value = "proggy tiny" },
            { idx = "autoban_first_delay", type = "Slider", value = "0" },
            { idx = "hit_effects_selected", type = "Dropdown", mutli = true, value = { ["Electricity"] = true, ["phantom forces"] = true } },
            { idx = "esp_name_color2", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "chat_spam_mode", type = "Dropdown", value = "custom" },
            { idx = "sunrays_spread", type = "Slider", value = "1" },
            { idx = "aimbot_delay_smooth_jump", type = "Slider", value = "10" },
            { idx = "esp_flag_health_text_color2", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_skeleton_color2", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_body_transparency", type = "Slider", value = "100" },
            { idx = "atmosphere_density", type = "Slider", value = "0.4" },
            { idx = "esp_box_rotation_speed", type = "Slider", value = "0.1" },
            { idx = "skybox_value", type = "Dropdown", value = "Heaven" },
            { idx = "weapon_filter", type = "Input", text = "" },
            { idx = "custom_tracer_emission", type = "Slider", value = "1" },
            { idx = "animation_player_end_position", type = "Slider", value = "100" },
            { idx = "aimbot_fov_lerp", type = "Slider", value = "0.25" },
            { idx = "weather_value", type = "Dropdown", value = "Rain" },
            { idx = "auto_queue_mode", type = "Dropdown", value = "1v1" },
            { idx = "color_correction_tint", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "aimbot_outline_color1", type = "ColorPicker", transparency = 0.786363636363636, value = "c576bd" },
            { idx = "esp_effects_particle_value", type = "Dropdown", mutli = true, value = { ["glowing"] = true } },
            { idx = "atmosphere_decay", type = "ColorPicker", transparency = 0, value = "fecaff" },
            { idx = "viewmodel_body_transparency", type = "Slider", value = "100" },
            { idx = "target_ui_position_y", type = "Slider", value = "70" },
            { idx = "silent_fill_color1", type = "ColorPicker", transparency = 0.85, value = "823b75" },
            { idx = "movement_maul_slam_multiplier", type = "Slider", value = "1" },
            { idx = "crosshair_thickness", type = "Slider", value = "2" },
            { idx = "target_hit_notify_duration", type = "Slider", value = "1" },
            { idx = "esp_distance_color2", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_name_color3", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "NotificationPositionX", type = "Slider", value = "50" },
            { idx = "NotificationColorsOutline", type = "ColorPicker", transparency = 0, value = "323232" },
            { idx = "NotificationColorsAccent", type = "ColorPicker", transparency = 0, value = "0055ff" },
            { idx = "KeybindMenuTransparency", type = "Slider", value = "50" },
            { idx = "MenuKeybind", type = "KeyPicker", key = "RightShift", mode = "Toggle" },
            { idx = "targeting_closest_part_blacklist", type = "Dropdown", mutli = true, value = { ["LeftFoot"] = true, ["RightLowerArm"] = true, ["LeftHand"] = true, ["LeftLowerArm"] = true, ["RightLowerLeg"] = true, ["RightHand"] = true, ["RightFoot"] = true, ["LeftLowerLeg"] = true } },
            { idx = "indicator_settings", type = "Dropdown", mutli = true, value = {} },
            { idx = "atmosphere_color", type = "ColorPicker", transparency = 0, value = "ffc8fd" },
            { idx = "shoot_sound_change_value", type = "Dropdown", mutli = false, value = "crossbow" },
            { idx = "movement_velocitykeybind", type = "KeyPicker", key = "G", mode = "Always" },
            { idx = "aimbot_smoothing", type = "Slider", value = "100" },
            { idx = "auto_select_Melee", type = "Dropdown", value = "Riot Shield" },
            { idx = "name_spoofer_name", type = "Input", text = "" },
            { idx = "autoban_second", type = "Dropdown", value = "Katana" },
            { idx = "movement_noclipkeybind", type = "KeyPicker", key = "X", mode = "Toggle" },
            { idx = "target_tracer_customization", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "lighting_colorColorShift_Top", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "movement_slideboostvalue", type = "Slider", value = "2.5" },
            { idx = "ambience_volume", type = "Slider", value = "0.5" },
            { idx = "autoban_second_delay", type = "Slider", value = "0" },
            { idx = "esp_box_color1", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "autoban_map_delay", type = "Slider", value = "0" },
            { idx = "custom_tracer_speed", type = "Slider", value = "2" },
            { idx = "ragebot_settings", type = "Dropdown", mutli = true, value = { ["swap weapons when empty"] = true, ["prefer projectile weapon"] = true } },
            { idx = "animation_player_speed", type = "Slider", value = "1" },
            { idx = "viewmodel_recoil", type = "Slider", value = "0" },
            { idx = "camera_aspect_ratio_y", type = "Slider", value = "1" },
            { idx = "animation_player_value", type = "Dropdown", mutli = false, value = "solar system" },
            { idx = "indicator_ragebot_status_color", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "anti_aim_floor_hide_keybind", type = "KeyPicker", key = "...", mode = "Always" },
            { idx = "anti_aim_custom_yaw", type = "Slider", value = "0" },
            { idx = "aimbot_fill_color3", type = "ColorPicker", transparency = 0.818181818181818, value = "000000" },
            { idx = "anti_aim_custom_pitch", type = "Slider", value = "-180" },
            { idx = "ragebot_void_spam_hide", type = "Slider", value = "0.25" },
            { idx = "third_person_keybind", type = "KeyPicker", key = "H", mode = "Toggle" },
            { idx = "esp_healthbar_color_middle", type = "ColorPicker", transparency = 0, value = "bc75ba" },
            { idx = "movement_double_jump_height_multiplier", type = "Slider", value = "2" },
            { idx = "esp_weapon_color1", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "targeting_ignore_protected_settings", type = "Dropdown", mutli = true, value = { ["katana deflecting"] = true, ["blocked by riot shield"] = true } },
            { idx = "lighting_colorAmbient", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "camera_blur", type = "Slider", value = "0" },
            { idx = "aimbot_fov_settings", type = "Dropdown", mutli = true, value = { ["position on target"] = true, ["position on barrel"] = true } },
            { idx = "esp_flag_prefix", type = "Dropdown", mutli = false, value = "full" },
            { idx = "target_hit_notify_text", type = "Dropdown", mutli = true, value = { ["Hit {NAME} for {DMG} in the {PART}"] = true } },
            { idx = "lighting_number_ExposureCompensation", type = "Slider", value = "-1.1" },
            { idx = "ragebot_mode", type = "Dropdown", value = "gun" },
            { idx = "target_highlight_fill", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "esp_healthbar_health_lerp", type = "Slider", value = "0.05" },
            { idx = "exploits_firerate", type = "Slider", value = "15" },
            { idx = "esp_box_color2", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "indicator_ammo_divider_color", type = "ColorPicker", transparency = 0, value = "f296ee" },
            { idx = "crosshair_settings", type = "Dropdown", mutli = true, value = { ["position on target"] = true } },
            { idx = "NotificationPositionY", type = "Slider", value = "60" },
            { idx = "animation_player_custom_input", type = "Input", text = "" },
            { idx = "crosshair_length", type = "Slider", value = "13" },
            { idx = "targeting_maxdistance", type = "Slider", value = "250" },
            { idx = "lighting_colorColorShift_Bottom", type = "ColorPicker", transparency = 0, value = "ffffff" },
            { idx = "crosshair_rotation", type = "Slider", value = "0" }
        }
    }
}
